language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*

matrix:
  exclude:
    - php: '5.4'
      env: SYMFONY_VERSION=3.1.*
    - php: '5.4'
      env: SYMFONY_VERSION=3.2.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update

after_success:
  - composer global require satooshi/php-coveralls
  - travis_retry php $HOME/.composer/vendor/bin/coveralls -v
